import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import SkyflowProvider from "./provider/SkyflowProvider";
import ClientWrapper from "./provider/ClientWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* SkyflowProvider is used to provide the Skyflow configuration to the application */}
        <SkyflowProvider>
        {children}
        </SkyflowProvider>
       {/* Uncomment the ClientWrapper if you want to use dynamic import for SkyflowProvider */}
        {/* <ClientWrapper>
        {children}
        </ClientWrapper> */}
      </body>
    </html>
  );
}
