name: Internal Release

on:
  push:
    tags-ignore:
      - '*.*'
    paths-ignore:
      - 'package-lock.json'
      - '*.md'
    branches:
      - release/*

jobs:
  build-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_ACTIONS }}
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: 14.17.6
      - run: npm install

      - name: npm build
        run: npm run build

      - name: build react-sdk
        run: |
          curl -u ${{ secrets.JFROG_USERNAME }}:${{ secrets.JFROG_PASSWORD }} https://prekarilabs.jfrog.io/prekarilabs/api/npm/auth/ > ~/.npmrc
          npm config set registry https://prekarilabs.jfrog.io/prekarilabs/api/npm/npm/
          npm config set unsafe-perm true
          npm run build

      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 1.0.0

      - name: Bump Version
        run: |
          chmod +x ./scripts/bump_version.sh
          ./scripts/bump_version.sh "${{ steps.previoustag.outputs.tag }}" "$(git rev-parse --short "$GITHUB_SHA")"

      - name: Commit changes
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git add package.json
          git commit -m "[AUTOMATED] Private Release ${{ steps.previoustag.outputs.tag }}-dev.$(git rev-parse --short $GITHUB_SHA)"
          git push origin -f

      - name: publish to jfrog
        run: |
          npm publish
